# Generated by Django 5.2.5 on 2025-09-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il_kodu', models.CharField(max_length=2, unique=True)),
                ('il_adi', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'db_table': 'il',
                'ordering': ['il_adi'],
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilce_adi', models.CharField(max_length=50)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='sube_yonetimi.il')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'db_table': 'ilce',
                'ordering': ['ilce_adi'],
                'unique_together': {('il', 'ilce_adi')},
            },
        ),
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sube_kodu', models.CharField(help_text='Şube kodu (kullanıcı girecek, örn: ANK001)', max_length=10, unique=True)),
                ('sube_adi', models.CharField(max_length=200)),
                ('sube_sinifi', models.CharField(choices=[('1', '1. Sınıf (Büyük) - 25 Personel'), ('2', '2. Sınıf (Orta) - 15 Personel'), ('3', '3. Sınıf (Küçük) - 8 Personel')], max_length=1)),
                ('durum', models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], default='A', max_length=1)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subeler', to='sube_yonetimi.ilce')),
            ],
            options={
                'verbose_name': 'Şube',
                'verbose_name_plural': 'Şubeler',
                'db_table': 'sube',
                'ordering': ['sube_kodu'],
            },
        ),
    ]
