# Generated by Django 5.2.5 on 2025-08-29 08:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrediFaizOrani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kredi_turu', models.CharField(choices=[('bireysel', 'Bireysel Kredi'), ('konut', 'Konut Kredisi'), ('tasit', 'Taşıt Kredisi')], max_length=20, unique=True, verbose_name='Kredi Türü')),
                ('min_faiz_orani', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Faiz Oranı (%)')),
                ('max_faiz_orani', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maksimum Faiz Oranı (%)')),
                ('varsayilan_faiz_orani', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Varsayılan Faiz Oranı (%)')),
                ('min_tutar', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12, verbose_name='Minimum Tutar (TL)')),
                ('max_tutar', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12, verbose_name='Maksimum Tutar (TL)')),
                ('min_vade_ay', models.PositiveIntegerField(default=6, verbose_name='Minimum Vade (Ay)')),
                ('max_vade_ay', models.PositiveIntegerField(default=120, verbose_name='Maksimum Vade (Ay)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Kredi Faiz Oranı',
                'verbose_name_plural': 'Kredi Faiz Oranları',
            },
        ),
        migrations.CreateModel(
            name='KrediHesaplama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kredi_turu', models.CharField(choices=[('bireysel', 'Bireysel Kredi'), ('konut', 'Konut Kredisi'), ('tasit', 'Taşıt Kredisi')], default='bireysel', max_length=20, verbose_name='Kredi Türü')),
                ('kredi_tutari', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))], verbose_name='Kredi Tutarı (TL)')),
                ('vade_ay', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Vade (Ay)')),
                ('faiz_orani', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Faiz Oranı (%)')),
                ('aylik_taksit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Aylık Taksit (TL)')),
                ('toplam_odeme', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Ödeme (TL)')),
                ('toplam_faiz', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Faiz (TL)')),
                ('hesaplama_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Hesaplama Tarihi')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('hesaplama_detaylari', models.JSONField(blank=True, default=dict, verbose_name='Hesaplama Detayları')),
            ],
            options={
                'verbose_name': 'Kredi Hesaplama',
                'verbose_name_plural': 'Kredi Hesaplamaları',
                'ordering': ['-hesaplama_tarihi'],
                'indexes': [models.Index(fields=['kredi_turu', 'hesaplama_tarihi'], name='hesaplama_k_kredi_t_7a52f3_idx'), models.Index(fields=['hesaplama_tarihi'], name='hesaplama_k_hesapla_cdb706_idx')],
            },
        ),
    ]
