# Generated by Django 5.2.10 on 2026-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrediBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_adi', models.CharField(max_length=100)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(default='Beklemede', max_length=20)),
            ],
        ),
    ]
