# Generated by Django 5.2.10 on 2026-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullandirim_listeleme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrediRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_no', models.CharField(max_length=20, unique=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('notlar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KrediBasvuru',
        ),
    ]
