# Generated by Django 5.2.5 on 2025-09-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriTemel',
            fields=[
                ('musteri_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('musteri_turu', models.CharField(choices=[('bireysel', 'Bireysel Müşteri'), ('tfgk', 'TFGK (Ticari Faaliyeti Olan Gerçek Kişi)'), ('tuzel', 'Tüzel Kişi')], max_length=20)),
                ('durum_kodu', models.BooleanField(default=True, help_text='Aktif/Pasif durumu')),
                ('vergi_numarasi', models.CharField(blank=True, max_length=10, null=True)),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Müşteri Temel',
                'verbose_name_plural': 'Müşteri Temel Bilgileri',
                'db_table': 'musteri_temel',
            },
        ),
        migrations.CreateModel(
            name='MusteriGercek',
            fields=[
                ('musteri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gercek_kisi', serialize=False, to='musteri_yonetimi.musteritemel')),
                ('tckn', models.CharField(max_length=11)),
                ('adi', models.CharField(max_length=50)),
                ('soyadi', models.CharField(max_length=50)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('cinsiyet', models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=10, null=True)),
                ('medeni_hal', models.CharField(blank=True, choices=[('Bekar', 'Bekar'), ('Evli', 'Evli'), ('Boşanmış', 'Boşanmış'), ('Dul', 'Dul')], max_length=20, null=True)),
                ('meslek', models.CharField(blank=True, max_length=100, null=True)),
                ('nace_kodu', models.CharField(blank=True, max_length=20, null=True)),
                ('isletme_unvani', models.CharField(blank=True, max_length=200, null=True)),
                ('is_adresi', models.TextField(blank=True, null=True)),
                ('oda_kaydi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Gerçek Kişi',
                'verbose_name_plural': 'Gerçek Kişiler',
                'db_table': 'musteri_gercek',
            },
        ),
        migrations.CreateModel(
            name='MusteriTuzel',
            fields=[
                ('musteri', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tuzel_kisi', serialize=False, to='musteri_yonetimi.musteritemel')),
                ('sirket_unvani', models.CharField(max_length=200)),
                ('sirket_turu', models.CharField(blank=True, choices=[('Limited Şirketi', 'Limited Şirketi'), ('Anonim Şirket', 'Anonim Şirket'), ('Komandit Şirket', 'Komandit Şirket'), ('Kolektif Şirket', 'Kolektif Şirket')], max_length=50, null=True)),
                ('kurulus_tarihi', models.DateField(blank=True, null=True)),
                ('ticaret_sicil_no', models.CharField(blank=True, max_length=50, null=True)),
                ('nace_kodu', models.CharField(blank=True, max_length=20, null=True)),
                ('yetkili_adi', models.CharField(max_length=50)),
                ('yetkili_soyadi', models.CharField(max_length=50)),
                ('yetkili_tckn', models.CharField(max_length=11)),
                ('yetkili_gorevi', models.CharField(blank=True, max_length=100, null=True)),
                ('yetkili_temsil_yetkisi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Tüzel Kişi',
                'verbose_name_plural': 'Tüzel Kişiler',
                'db_table': 'musteri_tuzel',
            },
        ),
        migrations.CreateModel(
            name='MusteriEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_tipi', models.CharField(choices=[('kisisel', 'Kişisel'), ('is', 'İş'), ('diger', 'Diğer')], default='kisisel', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailler', to='musteri_yonetimi.musteritemel')),
            ],
            options={
                'verbose_name': 'Müşteri Email',
                'verbose_name_plural': 'Müşteri Emailleri',
                'db_table': 'musteri_email',
            },
        ),
        migrations.CreateModel(
            name='MusteriAdres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField()),
                ('adres_tipi', models.CharField(choices=[('ev', 'Ev Adresi'), ('is', 'İş Adresi'), ('diger', 'Diğer')], default='ev', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresler', to='musteri_yonetimi.musteritemel')),
            ],
            options={
                'verbose_name': 'Müşteri Adres',
                'verbose_name_plural': 'Müşteri Adresleri',
                'db_table': 'musteri_adres',
            },
        ),
        migrations.CreateModel(
            name='MusteriNotlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_baslik', models.CharField(max_length=200)),
                ('not_icerik', models.TextField()),
                ('olusturan', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='musteri_yonetimi.musteritemel')),
            ],
            options={
                'verbose_name': 'Müşteri Notu',
                'verbose_name_plural': 'Müşteri Notları',
                'db_table': 'musteri_notlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusteriTelefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('telefon_tipi', models.CharField(choices=[('cep', 'Cep Telefonu'), ('ev', 'Ev Telefonu'), ('is', 'İş Telefonu'), ('diger', 'Diğer')], default='cep', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonlar', to='musteri_yonetimi.musteritemel')),
            ],
            options={
                'verbose_name': 'Müşteri Telefon',
                'verbose_name_plural': 'Müşteri Telefonları',
                'db_table': 'musteri_telefon',
            },
        ),
        migrations.CreateModel(
            name='MusteriOrtak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('pay', models.DecimalField(decimal_places=2, help_text='Yüzde olarak', max_digits=5)),
                ('tckn', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortaklar', to='musteri_yonetimi.musterituzel')),
            ],
            options={
                'verbose_name': 'Müşteri Ortağı',
                'verbose_name_plural': 'Müşteri Ortakları',
                'db_table': 'musteri_ortak',
            },
        ),
    ]
