# Generated by Django 5.2.10 on 2026-01-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musteri_yonetimi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusteriNotlari',
        ),
    ]
