# Generated by Django 5.2.5 on 2025-09-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musteri_yonetimi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrediHesabi',
            fields=[
                ('kredi_hesap_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('kredi_turu', models.CharField(choices=[('ihtiyac', 'İhtiyaç Kredisi'), ('konut', 'Konut Kredisi'), ('tasit', 'Taşıt Kredisi')], max_length=20)),
                ('kredi_tutari', models.DecimalField(decimal_places=2, help_text='Ana kredi tutarı', max_digits=15)),
                ('doviz_cinsi', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini')], default='TRY', max_length=3)),
                ('vade', models.PositiveIntegerField(help_text='Vade (ay)')),
                ('aylik_faiz_orani', models.DecimalField(decimal_places=4, help_text='Aylık faiz oranı (%)', max_digits=5)),
                ('masraf_tutari', models.DecimalField(decimal_places=2, default=0, help_text='Masraf tutarı', max_digits=10)),
                ('aylik_odeme', models.DecimalField(decimal_places=2, help_text='Aylık ödeme tutarı', max_digits=15)),
                ('toplam_geri_odeme', models.DecimalField(decimal_places=2, help_text='Toplam geri ödeme tutarı', max_digits=15)),
                ('kalan_anapara', models.DecimalField(decimal_places=2, help_text='Kalan anapara', max_digits=15)),
                ('kalan_vade', models.PositiveIntegerField(help_text='Kalan vade (ay)')),
                ('aktif', models.BooleanField(default=True)),
                ('acilis_tarihi', models.DateField(auto_now_add=True)),
                ('kapanis_tarihi', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kredi_hesaplari', to='musteri_yonetimi.musteritemel')),
            ],
            options={
                'verbose_name': 'Kredi Hesabı',
                'verbose_name_plural': 'Kredi Hesapları',
                'db_table': 'kredi_hesabi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KrediOdemeHareketleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tarihi', models.DateTimeField(auto_now_add=True)),
                ('hareket_turu', models.CharField(choices=[('odeme', 'Taksit Ödemesi'), ('erken_odeme', 'Erken Ödeme'), ('gecikme_faizi', 'Gecikme Faizi'), ('masraf', 'Masraf')], max_length=20)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aciklama', models.TextField(blank=True)),
                ('taksit_no', models.PositiveIntegerField(blank=True, null=True)),
                ('islem_yapan', models.CharField(max_length=20)),
                ('kredi_hesabi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='kullandirim.kredihesabi')),
            ],
            options={
                'verbose_name': 'Kredi Hareketi',
                'verbose_name_plural': 'Kredi Hareketleri',
                'db_table': 'kredi_odeme_hareketleri',
                'ordering': ['-hareket_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KrediOdemePlanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taksit_no', models.PositiveIntegerField()),
                ('vade_tarihi', models.DateField()),
                ('anapara_tutari', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faiz_tutari', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taksit_tutari', models.DecimalField(decimal_places=2, max_digits=15)),
                ('kalan_bakiye', models.DecimalField(decimal_places=2, max_digits=15)),
                ('odendi_mi', models.BooleanField(default=False)),
                ('odeme_tarihi', models.DateField(blank=True, null=True)),
                ('kredi_hesabi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odeme_plani', to='kullandirim.kredihesabi')),
            ],
            options={
                'verbose_name': 'Ödeme Planı',
                'verbose_name_plural': 'Ödeme Planları',
                'db_table': 'kredi_odeme_plani',
                'ordering': ['taksit_no'],
                'unique_together': {('kredi_hesabi', 'taksit_no')},
            },
        ),
    ]
